# action.yml
name: 'Build Jenkins job'
description: 'Trigger jenkins job'
inputs:
  jenkins-url:
    description: 'jenkins server url'
    required: true
  jenkins-token:
    description: 'token to access jenkins server'
    required: true
  user:
    description: "user name"
    required: true
  job-path:
    description: 'job/folder_name/job/job_name'
    required: true
  job-params:
    description: "params to run the job. JSON string. i.e '{'param1': 'value1', 'param2': 'value2'}' "
    required: false
  include-logs:
    description: "Include the logs in the output"
    required: false

outputs:
  job_status:
    description: 'Build status'
  job_number:
    description: 'Build number'
  job_url:
    description: 'Build URL'
  job_log_info:
    description: 'Build logs that have been b64 encoded'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.jenkins-url}}
    - ${{ inputs.jenkins-token}}
    - ${{ inputs.user}}
    - ${{ inputs.job-path }}
    - ${{ inputs.job-params}}
    - ${{ inputs.include-logs}}

branding:
  icon: 'arrow-right-circle'
  color: 'blue'